In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('data/OnlineRetail.csv', encoding='latin1')

In [6]:
# first 20 rows

df.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,12/1/2010 8:34,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047.0,United Kingdom
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,12/1/2010 8:34,4.95,13047.0,United Kingdom
16,536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047.0,United Kingdom
17,536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
18,536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047.0,United Kingdom
19,536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,13047.0,United Kingdom

In [7]:
# how many rows and columns

df.shape

(541909, 8)

In [8]:
# column types and null counts

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [9]:
# how many missing values per column

df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
# removing null values

df = df.dropna(subset=['CustomerID'])
print("After removing all null CustomerIDs:", df.shape)

After removing all null CustomerIDs: (406829, 8)

In [11]:
#Cancelled Orders

cancelled = df[df['InvoiceNo'].astype(str).str.startswith('C')]
print(cancelled.shape)
print(cancelled.head(10))

(8905, 8)
    InvoiceNo StockCode                        Description  Quantity  \
141   C536379         D                           Discount        -1
154   C536383    35004C    SET OF 3 COLOURED  FLYING DUCKS        -1
235   C536391     22556     PLASTERS IN TIN CIRCUS PARADE        -12
236   C536391     21984   PACK OF 12 PINK PAISLEY TISSUES        -24
237   C536391     21983   PACK OF 12 BLUE PAISLEY TISSUES        -24
238   C536391     21980  PACK OF 12 RED RETROSPOT TISSUES        -24
239   C536391     21484        CHICK GREY HOT WATER BOTTLE       -12
240   C536391     22557   PLASTERS IN TIN VINTAGE PAISLEY        -12
241   C536391     22553             PLASTERS IN TIN SKULLS       -24
939   C536506     22960           JAM MAKING SET WITH JARS        -6

         InvoiceDate  UnitPrice  CustomerID         Country
141   12/1/2010 9:41      27.50     14527.0  United Kingdom
154   12/1/2010 9:49       4.65     15311.0  United Kingdom
235  12/1/2010 10:24       1.65     17548.0  United Kingdom
236  12/1/2010 10:24       0.29     17548.0  United Kingdom
237  12/1/2010 10:24       0.29     17548.0  United Kingdom
238  12/1/2010 10:24       0.29     17548.0  United Kingdom
239  12/1/2010 10:24       3.45     17548.0  United Kingdom
240  12/1/2010 10:24       1.65     17548.0  United Kingdom
241  12/1/2010 10:24       1.65     17548.0  United Kingdom
939  12/1/2010 12:38       4.25     17897.0  United Kingdom

In [12]:
#Removing cancelled orders

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]
print("After removing cancellations:", df.shape)

After removing cancellations: (397924, 8)

In [13]:
#Removing negative and zero quantities 

df = df[df['Quantity'] > 0]
print("After removing zero and negative quantities:", df.shape)

After removing zero and negative quantities: (397924, 8)

In [14]:
#Removing zero and negative prices

df = df[df['UnitPrice'] > 0]
print("After removing zero and negative prices:", df.shape)

After removing zero and negative prices: (397884, 8)

In [15]:
#Resetting Index

df = df.reset_index(drop=True)
print("Final Cleaned Dataset:", df.shape)
print(df.head(20))

Final Cleaned Dataset: (397884, 8)
   InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1     536365     71053                  WHITE METAL LANTERN         6
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
5     536365     22752         SET 7 BABUSHKA NESTING BOXES         2
6     536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6
7     536366     22633               HAND WARMER UNION JACK         6
8     536366     22632            HAND WARMER RED POLKA DOT         6
9     536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32
10    536367     22745           POPPY'S PLAYHOUSE BEDROOM          6
11    536367     22748            POPPY'S PLAYHOUSE KITCHEN         6
12    536367     22749    FELTCRAFT PRINCESS CHARLOTTE DOLL         8
13    536367     22310              IVORY KNITTED MUG COSY          6
14    536367     84969   BOX OF 6 ASSORTED COLOUR TEASPOONS         6
15    536367     22623        BOX OF VINTAGE JIGSAW BLOCKS          3
16    536367     22622       BOX OF VINTAGE ALPHABET BLOCKS         2
17    536367     21754             HOME BUILDING BLOCK WORD         3
18    536367     21755             LOVE BUILDING BLOCK WORD         3
19    536367     21777          RECIPE BOX WITH METAL HEART         4

       InvoiceDate  UnitPrice  CustomerID         Country
0   12/1/2010 8:26       2.55     17850.0  United Kingdom
1   12/1/2010 8:26       3.39     17850.0  United Kingdom
2   12/1/2010 8:26       2.75     17850.0  United Kingdom
3   12/1/2010 8:26       3.39     17850.0  United Kingdom
4   12/1/2010 8:26       3.39     17850.0  United Kingdom
5   12/1/2010 8:26       7.65     17850.0  United Kingdom
6   12/1/2010 8:26       4.25     17850.0  United Kingdom
7   12/1/2010 8:28       1.85     17850.0  United Kingdom
8   12/1/2010 8:28       1.85     17850.0  United Kingdom
9   12/1/2010 8:34       1.69     13047.0  United Kingdom
10  12/1/2010 8:34       2.10     13047.0  United Kingdom
11  12/1/2010 8:34       2.10     13047.0  United Kingdom
12  12/1/2010 8:34       3.75     13047.0  United Kingdom
13  12/1/2010 8:34       1.65     13047.0  United Kingdom
14  12/1/2010 8:34       4.25     13047.0  United Kingdom
15  12/1/2010 8:34       4.95     13047.0  United Kingdom
16  12/1/2010 8:34       9.95     13047.0  United Kingdom
17  12/1/2010 8:34       5.95     13047.0  United Kingdom
18  12/1/2010 8:34       5.95     13047.0  United Kingdom
19  12/1/2010 8:34       7.95     13047.0  United Kingdom

In [16]:
print(df.dtypes)

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [17]:
# converting customerid from float to int

df['CustomerID'] = df['CustomerID'].astype(int)
print(df['CustomerID'].dtype)
print(df['CustomerID'].head())

int64
0    17850
1    17850
2    17850
3    17850
4    17850
Name: CustomerID, dtype: int64

In [18]:
# convertng InvoiceDate to datetime dtype

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print(df['InvoiceDate'].dtype)
print(df['InvoiceDate'].head())

datetime64[ns]
0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[ns]

In [19]:
# null check

print(df.isnull().sum())

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [20]:
print(df.shape)
print(df.dtypes)
print(df.head())

(397884, 8)
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55       17850  United Kingdom
1 2010-12-01 08:26:00       3.39       17850  United Kingdom
2 2010-12-01 08:26:00       2.75       17850  United Kingdom
3 2010-12-01 08:26:00       3.39       17850  United Kingdom
4 2010-12-01 08:26:00       3.39       17850  United Kingdom

In [21]:
# Extracting InvoiceMonth from InvoiceDate

df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')
df.InvoiceMonth.head()

0    2010-12
1    2010-12
2    2010-12
3    2010-12
4    2010-12
Name: InvoiceMonth, dtype: period[M]

In [22]:
#Each Customer's First Purchase Month

cohort_month = df.groupby('CustomerID')['InvoiceMonth'].min().reset_index()
cohort_month.columns = ['CustomerID', 'CohortMonth']
print(cohort_month.head(20))
print(cohort_month.shape)

    CustomerID CohortMonth
0        12346     2011-01
1        12347     2010-12
2        12348     2010-12
3        12349     2011-11
4        12350     2011-02
5        12352     2011-02
6        12353     2011-05
7        12354     2011-04
8        12355     2011-05
9        12356     2011-01
10       12357     2011-11
11       12358     2011-07
12       12359     2011-01
13       12360     2011-05
14       12361     2011-02
15       12362     2011-02
16       12363     2011-04
17       12364     2011-08
18       12365     2011-02
19       12367     2011-12
(4338, 2)

In [23]:
#Merging CohortMonth Back Into Main Dataframe

df = df.merge(cohort_month, on='CustomerID', how='left')
print(df.head(20))
print(df.shape)

   InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1     536365     71053                  WHITE METAL LANTERN         6
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
5     536365     22752         SET 7 BABUSHKA NESTING BOXES         2
6     536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6
7     536366     22633               HAND WARMER UNION JACK         6
8     536366     22632            HAND WARMER RED POLKA DOT         6
9     536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32
10    536367     22745           POPPY'S PLAYHOUSE BEDROOM          6
11    536367     22748            POPPY'S PLAYHOUSE KITCHEN         6
12    536367     22749    FELTCRAFT PRINCESS CHARLOTTE DOLL         8
13    536367     22310              IVORY KNITTED MUG COSY          6
14    536367     84969   BOX OF 6 ASSORTED COLOUR TEASPOONS         6
15    536367     22623        BOX OF VINTAGE JIGSAW BLOCKS          3
16    536367     22622       BOX OF VINTAGE ALPHABET BLOCKS         2
17    536367     21754             HOME BUILDING BLOCK WORD         3
18    536367     21755             LOVE BUILDING BLOCK WORD         3
19    536367     21777          RECIPE BOX WITH METAL HEART         4

           InvoiceDate  UnitPrice  CustomerID         Country InvoiceMonth  \
0  2010-12-01 08:26:00       2.55       17850  United Kingdom      2010-12
1  2010-12-01 08:26:00       3.39       17850  United Kingdom      2010-12
2  2010-12-01 08:26:00       2.75       17850  United Kingdom      2010-12
3  2010-12-01 08:26:00       3.39       17850  United Kingdom      2010-12
4  2010-12-01 08:26:00       3.39       17850  United Kingdom      2010-12
5  2010-12-01 08:26:00       7.65       17850  United Kingdom      2010-12
6  2010-12-01 08:26:00       4.25       17850  United Kingdom      2010-12
7  2010-12-01 08:28:00       1.85       17850  United Kingdom      2010-12
8  2010-12-01 08:28:00       1.85       17850  United Kingdom      2010-12
9  2010-12-01 08:34:00       1.69       13047  United Kingdom      2010-12
10 2010-12-01 08:34:00       2.10       13047  United Kingdom      2010-12
11 2010-12-01 08:34:00       2.10       13047  United Kingdom      2010-12
12 2010-12-01 08:34:00       3.75       13047  United Kingdom      2010-12
13 2010-12-01 08:34:00       1.65       13047  United Kingdom      2010-12
14 2010-12-01 08:34:00       4.25       13047  United Kingdom      2010-12
15 2010-12-01 08:34:00       4.95       13047  United Kingdom      2010-12
16 2010-12-01 08:34:00       9.95       13047  United Kingdom      2010-12
17 2010-12-01 08:34:00       5.95       13047  United Kingdom      2010-12
18 2010-12-01 08:34:00       5.95       13047  United Kingdom      2010-12
19 2010-12-01 08:34:00       7.95       13047  United Kingdom      2010-12

   CohortMonth
0      2010-12
1      2010-12
2      2010-12
3      2010-12
4      2010-12
5      2010-12
6      2010-12
7      2010-12
8      2010-12
9      2010-12
10     2010-12
11     2010-12
12     2010-12
13     2010-12
14     2010-12
15     2010-12
16     2010-12
17     2010-12
18     2010-12
19     2010-12
(397884, 10)

In [24]:
#checking

df[['CustomerID', 'InvoiceMonth', 'CohortMonth']].head(50)

    CustomerID InvoiceMonth CohortMonth
0        17850      2010-12     2010-12
1        17850      2010-12     2010-12
2        17850      2010-12     2010-12
3        17850      2010-12     2010-12
4        17850      2010-12     2010-12
5        17850      2010-12     2010-12
6        17850      2010-12     2010-12
7        17850      2010-12     2010-12
8        17850      2010-12     2010-12
9        13047      2010-12     2010-12
10       13047      2010-12     2010-12
11       13047      2010-12     2010-12
12       13047      2010-12     2010-12
13       13047      2010-12     2010-12
14       13047      2010-12     2010-12
15       13047      2010-12     2010-12
16       13047      2010-12     2010-12
17       13047      2010-12     2010-12
18       13047      2010-12     2010-12
19       13047      2010-12     2010-12
20       13047      2010-12     2010-12
21       13047      2010-12     2010-12
22       13047      2010-12     2010-12
23       13047      2010-12     2010-12
24       13047      2010-12     2010-12
25       13047      2010-12     2010-12
26       12583      2010-12     2010-12
27       12583      2010-12     2010-12
28       12583      2010-12     2010-12
29       12583      2010-12     2010-12
30       12583      2010-12     2010-12
31       12583      2010-12     2010-12
32       12583      2010-12     2010-12
33       12583      2010-12     2010-12
34       12583      2010-12     2010-12
35       12583      2010-12     2010-12
36       12583      2010-12     2010-12
37       12583      2010-12     2010-12
38       12583      2010-12     2010-12
39       12583      2010-12     2010-12
40       12583      2010-12     2010-12
41       12583      2010-12     2010-12
42       12583      2010-12     2010-12
43       12583      2010-12     2010-12
44       12583      2010-12     2010-12
45       12583      2010-12     2010-12
46       13748      2010-12     2010-12
47       17850      2010-12     2010-12
48       17850      2010-12     2010-12
49       17850      2010-12     2010-12

In [25]:
print(df['CohortMonth'].nunique())
print(df['CohortMonth'].unique())

13
<PeriodArray>
['2010-12', '2011-01', '2011-02', '2011-03', '2011-04', '2011-05', '2011-06',
 '2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12']
Length: 13, dtype: period[M]

In [26]:
#TotalPrice Column

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
print(df['TotalPrice'].head(10))

0    15.30
1    20.34
2    22.00
3    20.34
4    20.34
5    15.30
6    25.50
7    11.10
8    11.10
9    54.08
Name: TotalPrice, dtype: float64

In [27]:
print(df['TotalPrice'].describe())

count    397884.000000
mean         22.397000
std         309.071041
min           0.001000
25%           4.680000
50%          11.800000
75%          19.800000
max      168469.600000
Name: TotalPrice, dtype: float64

In [28]:
#top 20 customers

top_customers = df.groupby('CustomerID')['TotalPrice'].sum().sort_values(ascending=False).head(20)
print(top_customers)

CustomerID
14646    280206.02
18102    259657.30
17450    194550.79
16446    168472.50
14911    143825.06
12415    124914.53
14156    117379.63
17511     91062.38
16029     81024.84
12346     77183.60
16684     66653.56
14096     65164.79
13694     65039.62
15311     60767.90
13089     58825.83
17949     58510.48
15769     56252.72
15061     54534.14
14298     51527.30
14088     50491.81
Name: TotalPrice, dtype: float64

In [29]:
#revenue by country

revenue_by_country = df.groupby('Country')['TotalPrice'].sum().sort_values(ascending=False).head(20)
print(revenue_by_country)

Country
United Kingdom     7308391.554
Netherlands         285446.340
EIRE                265545.900
Germany             228867.140
France              209024.050
Australia           138521.310
Spain                61577.110
Switzerland          56443.950
Belgium              41196.340
Sweden               38378.330
Japan                37416.370
Norway               36165.440
Portugal             33439.890
Finland              22546.080
Singapore            21279.290
Channel Islands      20450.440
Denmark              18955.340
Italy                17483.240
Cyprus               13590.380
Austria              10198.680
Name: TotalPrice, dtype: float64

In [30]:
#top 20 products

top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(20)
print(top_products)

Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        77916
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54415
JUMBO BAG RED RETROSPOT               46181
WHITE HANGING HEART T-LIGHT HOLDER    36725
ASSORTED COLOUR BIRD ORNAMENT         35362
PACK OF 72 RETROSPOT CAKE CASES       33693
POPCORN HOLDER                        30931
RABBIT NIGHT LIGHT                    27202
MINI PAINT SET VINTAGE                26076
PACK OF 12 LONDON TISSUES             25345
PACK OF 60 PINK PAISLEY CAKE CASES    24264
BROCADE RING PURSE                    22963
VICTORIAN GLASS HANGING T-LIGHT       22433
ASSORTED COLOURS SILK FAN             21876
RED  HARMONICA IN BOX                 20975
JUMBO BAG PINK POLKADOT               20165
SMALL POPCORN HOLDER                  18252
LUNCH BAG RED RETROSPOT               17697
60 TEATIME FAIRY CAKE CASES           17689
Name: Quantity, dtype: int64

In [31]:
#monthly revenue

monthly_revenue = df.groupby('InvoiceMonth')['TotalPrice'].sum().sort_values(ascending=False)
print(monthly_revenue)

InvoiceMonth
2011-11    1161817.380
2011-10    1039318.790
2011-09     952838.382
2011-05     678594.560
2011-06     661213.690
2011-08     645343.900
2011-07     600091.011
2011-03     595500.760
2010-12     572713.890
2011-01     569445.040
2011-12     518192.790
2011-04     469200.361
2011-02     447137.350
Freq: M, Name: TotalPrice, dtype: float64

In [32]:
# Reload raw data to examine cancellations separately

df_raw = pd.read_csv(r"C:/Users/sakin_xyc6lmd/OneDrive/Desktop/Infotact internship projects/SaaS-E-Commerce-Cohort-Retention-CLTV-Analysis-Infotact-Group-5---Project-1-/OnlineRetail.csv", encoding='latin1')
cancelled = df_raw[df_raw['InvoiceNo'].astype(str).str.startswith('C')]
print("Total cancelled orders:", cancelled.shape)
print(cancelled.head(20))

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/sakin_xyc6lmd/OneDrive/Desktop/Infotact internship projects/SaaS-E-Commerce-Cohort-Retention-CLTV-Analysis-Infotact-Group-5---Project-1-/OnlineRetail.csv'

In [ ]:
#which customer cancelled most

cancelled_by_customer = cancelled.groupby('CustomerID')['InvoiceNo'].count().sort_values(ascending=False).head(20)
print(cancelled_by_customer)

In [ ]:
#cancelled by country

cancelled_by_country = cancelled.groupby('Country')['InvoiceNo'].count().sort_values(ascending=False).head(10)
print(cancelled_by_country)